version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "user"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 5s
      timeout: 5s
      retries: 5
  discountaria-svc:
    image: discountaria
    restart: unless-stopped
    environment:
      - CONFIG_PATH=/config.yaml
    volumes:
      - ./config.local.yaml:/config.yaml
    ports:
      - "8009:80"
    entrypoint: sh -c "discountaria migrate up && discountaria run service"
    depends_on:
      postgres:
        condition: service_healthy